specVersion: 1.0.0
name: juno-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Cosmos (Juno)
  based SubQuery project
repository: "https://github.com/subquery/juno-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: juno-1
  endpoint: "https://juno.api.onfinality.io/public"
  dictionary: "https://api.subquery.network/sq/subquery/cosmos-juno-dictionary"
dataSources:
  - kind: cosmos/Runtime
    startBlock: 4415041
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/EventHandler
          filter:
            module: session
            method: NewSession
